### ISSUE TITLE
Make use of TimedStates in reports

### ISSUE THREAD

**Issue by martin-voigt** [strolch-li/strolch#6]
Right now, it is only possible to access parameters at Resource level or in ParameterBags as columns and as date range selector. Since a interesting data is also stored in TimedStates, they should be usable.

Use case from Susi project is: Create reports for PersonPickings, which are holds the information about which person tooks how many units of a product in a given time frame.

The TimedState looks like

`<TimedState Id="actualPickings" Name="Actual Pickings" Type="FloatState">
	<Value Time="2017-04-01T08:00:00.000+01:00" Value="1.0" />
	<Value Time="2017-04-01T16:00:00.000+01:00" Value="5.0" />
	<Value Time="2017-04-02T08:00:00.000+01:00" Value="6.0" />
	<Value Time="2017-04-02T16:00:00.000+01:00" Value="9.0" />
</TimedState>`

The following features would be helpful:

1.  Add a column to the report that access the last value of the state, like
`<Parameter Id="quantity" Name="Quantity" Type="String" Interpretation="Resource-Ref" Uom="PersonPicking" Value="TimedState/actualPickings/last Index="4" />`

2. Add two columns to the report the hold the time and the value of the states, like
`<Parameter Id="quantityAt" Name="Quantity At" Type="String" Interpretation="Resource-Ref" Uom="PersonPicking" Value="TimedState/actualPickings/time Index="4" />
<Parameter Id="quantity" Name="Quantity" Type="String" Interpretation="Resource-Ref" Uom="PersonPicking" Value="TimedState/actualPickings/value Index="5" />`

3. Make the timed states usable in the date range selector, like
`<Parameter Id="dateRangeSel" Name="Date Range Selector" Type="String" Interpretation="Resource-Ref" Uom="PersonPicking" Value="TimedState/actualPickings" />`

**Comment by eitch** [comment]
Never been used, so closing as stale
